<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Driver>
 */
class DriverFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->firstName(),
            'surname' => fake()->lastName(),
            'nationality' => fake()->randomElement([
                'Afghan',
                'Albanian',
                'Algerian',
                'Andorran',
                'Angolan',
                'Antiguan and barbudan',
                'Argentine',
                'Armenian',
                'Australian',
                'Austrian',
                'Azerbaijani',
                'Bahamian',
                'Bahraini',
                'Bangladeshi',
                'Barbadian',
                'Belarusian',
                'Belgian',
                'Belizean',
                'Beninese',
                'Bhutanese',
                'Bolivian',
                'Bosnian',
                'Botswanan',
                'Brazilian',
                'Bruneian',
                'Bulgarian',
                'Burkinabe',
                'Burundian',
                'Cambodian',
                'Cameroonian',
                'Canadian',
                'Cape Verdean',
                'Central African',
                'Chadian',
                'Chilean',
                'Chinese',
                'Colombian',
                'Comorian',
                'Congolese',
                'Costa Rican',
                'Ivorian',
                'Croatian',
                'Cuban',
                'Cypriot',
                'Czech',
                'Danish',
                'Djiboutian',
                'Dominican',
                'R_Dominican',
                'DR_Congolese',
                'Ecuadorian',
                'Egyptian',
                'Salvadoran',
                'Equatorial Guinean',
                'Eritrean',
                'Estonian',
                'Swazi',
                'Ethiopian',
                'Fijian',
                'Finnish',
                'French',
                'Gabonese',
                'Gambian',
                'Georgian',
                'German',
                'Ghanaian',
                'Greek',
                'Grenadian',
                'Guatemalan',
                'Bissau‑Guinean',
                'Guinean',
                'Guyanese',
                'Haitian',
                'Honduran',
                'Hungarian',
                'Icelander',
                'Indian',
                'Indonesian',
                'Iranian',
                'Iraqi',
                'Irish',
                'Israeli',
                'Italian',
                'Jamaican',
                'Japanese',
                'Jordanian',
                'Kazakhstani',
                'Kenyan',
                'I‑Kiribati',
                'Kuwaiti',
                'Kyrgyzstani',
                'Laotian',
                'Latvian',
                'Lebanese',
                'Mosotho',
                'Liberian',
                'Libyan',
                'Liechtensteiner',
                'Lithuanian',
                'Luxembourger',
                'Malagasy',
                'Malawian',
                'Malaysian',
                'Maldivian',
                'Malian',
                'Maltese',
                'Marshallese',
                'Mauritanian',
                'Mauritian',
                'Mexican',
                'Micronesian',
                'Moldovan',
                'Monégasque',
                'Mongolian',
                'Montenegrin',
                'Moroccan',
                'Mozambican',
                'Burmese',
                'Namibian',
                'Nauruan',
                'Nepalese',
                'Dutch',
                'New Zealander',
                'Nicaraguan',
                'Nigerien',
                'Nigerian',
                'North Korean',
                'North Macedonian',
                'Norwegian',
                'Omani',
                'Pakistani',
                'Palauan',
                'Palestinian',
                'Panamanian',
                'Papua New Guinean',
                'Paraguayan',
                'Peruvian',
                'Filipino',
                'Polish',
                'Portuguese',
                'Qatari',
                'Romanian',
                'Russian',
                'Rwandan',
                'Saint Kittian and Nevisian',
                'Saint Lucian',
                'Samoan',
                'San Marinese',
                'Sao Tomean',
                'Saudi Arabian',
                'Senegalese',
                'Serbian',
                'Seychellois',
                'Sierra Leonean',
                'Singaporean',
                'Slovakian',
                'Slovenian',
                'Solomon Islander',
                'Somali',
                'South African',
                'South Korean',
                'South Sudanese',
                'Spanish',
                'Sri Lankan',
                'Saint Vincentian',
                'Sudanese',
                'Surinamese',
                'Swedish',
                'Swiss',
                'Syrian',
                'Tajikistani',
                'Tanzanian',
                'Thai',
                'Timorese',
                'Togolese',
                'Tongan',
                'Trinidadian and Tobagonian',
                'Tunisian',
                'Turkish',
                'Turkmen',
                'Tuvaluan',
                'Ugandan',
                'Ukrainian',
                'Emirati',
                'British',
                'American',
                'Uruguayan',
                'Uzbekistani',
                'Ni-Vanuatu',
                'Venezuelan',
                'Vietnamese',
                'Yemeni',
                'Zambian',
                'Zimbabwean',
                null,
            ]),
            'status' => true,
        ];
    }
}
